#ifndef DATAHOLDERLOCALSERVERCOMMANDS_H
#define DATAHOLDERLOCALSERVERCOMMANDS_H


#define DATAHOLDER_REG              1 //A CLIENT SENDS ITS NAME (WRITER OR READER MODE)

#define DATAHOLDER_PINGSERV         2 //FROM SERVER TO CLIENT
#define DATAHOLDER_PINGCLNT         3 //FROM CLIENT TO SERVER


#define DATAHOLDER_ADD_POLLDATA     10 //A CLIENT SENDS DATA
#define DATAHOLDER_GET_POLLDATA     12 //A CLIENT ASKS FOR DATA



#endif // DATAHOLDERLOCALSERVERCOMMANDS_H
